# Generated by Django 3.2.18 on 2023-04-04 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_booking_confirmed'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='confirmed',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='table',
        ),
        migrations.RemoveField(
            model_name='user',
            name='is_staff',
        ),
        migrations.RemoveField(
            model_name='user',
            name='is_superuser',
        ),
        migrations.AlterField(
            model_name='booking',
            name='date_time',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
